import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { Navbar } from "~/components/Navbar";
import { PrimaryButton, TersierButton } from "~/components/Button";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>FiReddit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <Navbar />
        <div className="flex flex-1 flex-col  sm:flex-row">
          <aside className="order-first w-52 ">2</aside>
          <main className="flex-1">
            <header>
              <h1>FiReddit</h1>
              <PrimaryButton>Hello World</PrimaryButton>
              <TersierButton>Hello From tersier Button</TersierButton>
            </header>
          </main>
          <aside className="">right sidebar</aside>
        </div>
        <footer>footer</footer>
      </div>
    </>
  );
};

export default Home;
