import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { Navbar } from "~/components/Navbar";
import { PrimaryButton, TersierButton } from "~/components/Button";
import {
  FaArrowAltCircleUp,
  FaArrowDown,
  FaArrowUp,
  FaComment,
  FaPlus,
} from "react-icons/fa";
import { PostCard } from "~/components/Card";
import { useEffect } from "react";
const Home = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>FiReddit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header for Filtering Posts and creating posts */}
      <div className="flex min-h-screen flex-col">
        <Navbar />
        <div className="flex flex-1 flex-col  sm:flex-row">
          <aside className="w-52 border p-3 "></aside>
          <main className="flex w-full flex-1 flex-col p-2 px-7 md:mt-5">
            <div className=" flex w-full flex-col  gap-1">
              <PostCard
                postDate="20-20-2023"
                updatedAt="20-20-2023"
                username={"ZZZ"}
                userId="3f"
                tags={["javascript", "learning"]}
                commentCount={2}
                likeCount={2}
                postBody="hello world"
                title="Hello world from card"
              />
            </div>
          </main>
        </div>
      </div>
    </>
  );
};

export default Home;
